apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: default-domain
  namespace: garden
  annotations:
    dns.gardener.cloud/domain: shoot.example.com
    dns.gardener.cloud/provider: aws-route53
  labels:
    garden.sapcloud.io/role: default-domain
    gardener.cloud/role: default-domain
data:
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
