apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: <prefix>-gcp-vmx
  namespace: garden-dev
spec:
  cloudProfileName: gcp
  secretBindingName: shoot-operator-gcp
  purpose: evaluation
  region: europe-west1
  provider:
    type: gcp
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west1-c
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.250.0.0/16
    workers:
    - name: worker-test
      machine:
        type: n1-standard-16
        image:
          name: ubuntu
          version: 18.4.20200916-vmx
      minimum: 1
      maximum: 1
      volume:
        type: pd-standard
        size: 50Gi
      zones:
      - europe-west1-c
  networking:
    type: calico
    pods: 10.225.128.0/17
    nodes: 10.250.0.0/16
    services: 10.225.0.0/17
  kubernetes:
    version: 1.18.5
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  addons:
    kubernetesDashboard:
      enabled: true
    nginxIngress:
      enabled: true
