apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: kubevirt
  namespace: garden-dev
spec:
  cloudProfileName: kubevirt
  secretBindingName: kubevirt-credentials
  purpose: development
  region: europe-west1
  provider:
    type: kubevirt
    workers:
    - name: cpu-worker
      machine:
        type: standard-1
        image:
          name: ubuntu
          version: "18.04"
      minimum: 1
      maximum: 2
      volume:
        type: default
        size: 20Gi
      providerConfig:
        apiVersion: kubevirt.provider.extensions.gardener.cloud/v1alpha1
        kind: WorkerConfig
        disablePreAllocatedDataVolumes: true
      zones:
      - europe-west1-c
  networking:
    type: calico
    pods: 100.96.0.0/11
    nodes: 10.225.128.0/17
    services: 100.64.0.0/13
  kubernetes:
    version: 1.18.5
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
