---
apiVersion: kubevirt.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
clientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
etcd:
  storage:
    className: standard
    capacity: 5Gi
#healthCheckConfig:
#  syncPeriod: 30s