---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--kubevirt
  labels:
#    seed.gardener.cloud/provider: kubevirt
    shoot.gardener.cloud/provider: kubevirt
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--kubevirt
type: Opaque
data:
  kubeconfig: a3ViZWNvbmZpZw==
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--kubevirt
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: CloudProfile
  seed:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Shoot
    spec:
      networking:
        pods: 10.250.0.0/19
      kubernetes:
        version: 1.13.4
      hibernation:
        enabled: false
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: ControlPlane
metadata:
  name: control-plane
  namespace: shoot--foobar--kubevirt
spec:
  type: kubevirt
  region: default
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--kubevirt
  providerConfig:
    apiVersion: kubevirt.provider.extensions.gardener.cloud/v1alpha1
    kind: ControlPlaneConfig
    cloudControllerManager:
      featureGates:
        CustomResourceValidation: true
  infrastructureProviderStatus:
    apiVersion: kubevirt.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    networks:
    - name: default/shoot--dev--kubevirt-network-1
      default: true
