{{- if eq .Values.gardener.seed.provider "kubevirt" }}
{{- if .Values.config.etcd.storage.className }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.config.etcd.storage.className }}
  labels:
{{ include "labels" . | indent 4 }}
provisioner: {{ .Values.config.etcd.storage.provisioner }}
{{- if .Values.config.etcd.storage.parameters }}
parameters:
{{ toYaml .Values.config.etcd.storage.parameters | indent 2 }}
{{- end }}
{{- end }}
{{- end }}