machineClasses:
- name: class-1
  resources:
    requests:
      cpu: "100m"
      memory: "2Gi"
    limits:
      cpu: "300m"
      memory: "4Gi"
    overcommitGuestOverhead: true
  rootVolume:
    pvc:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    source:
      http:
        url: source-image-url
  additionalVolumes:
  - dataVolume:
      pvc:
        storageClassName: standard
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      source:
        blank: {}
  sshKeys:
  - "ssh-rsa AAAAB3..."
  networks:
  - name: default/net-conf
    default: true
  region: default
  zone: default
  tags:
  - kubernetes.io/cluster: foo
    kubernetes.io/role: node
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
    - 8.8.8.8
  memory:
    hugepages:
      pageSize: "2Mi"
  cpu:
    sockets: 2
    threads: 1
    cores: 1
  secret:
    cloudConfig: abc
    kubeconfig: abc
