machineClasses:
- name: class-1
  resources:
    requests:
      cpu: "100m"
      memory: "2Gi"
    limits:
      cpu: "300m"
      memory: "4Gi"
    overcommitGuestOverhead: true
  storageClassName: standard
  pvcSize: "10Gi"
  sourceURL: source-image-url
  sshKeys:
  - "ssh-rsa AAAAB3..."
  networks:
  - name: default/net-conf
    default: true
  region: default
  zone: default
  tags:
  - kubernetes.io/cluster: foo
    kubernetes.io/role: node
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
    - 8.8.8.8
  memory:
    hugepages:
      pageSize: "2Mi"
  cpu:
    sockets: 2
    threads: 1
    cores: 1
  secret:
    cloudConfig: abc
    kubeconfig: abc
