machineClasses:
- name: class-1
  storageClassName: standard
  pvcSize: "10Gi"
  sourceURL: source-image-url
  cpus: "1"
  memory: "4096M"
  sshKeys:
  - "ssh-rsa AAAAB3..."
  networks:
  - name: default/net-conf
    default: true
  region: default
  zone: default
  tags:
  - kubernetes.io/cluster: foo
    kubernetes.io/role: node
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
    - 8.8.8.8
  memoryFeatures:
    hugepages:
      pageSize: "2Mi"
  secret:
    cloudConfig: abc
    kubeconfig: abc
